services:
  - type: web
    name: luddy-room-reservation
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/room-reservation-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: PORT
        value: 8080
